[options]
library = "LightDM"
version = "1"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["../../gir-files/", "/usr/share/gir-1.0"]
work_mode = "sys"
single_version_file = true

external_libraries = [
    "Gio",
    "GLib",
    "GObject",
]

[crate_name_overrides]
"light_dm" = "lightdm"
