// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT
#![allow(deprecated)]

use crate::{ffi,MessageType,PromptType};
use glib::{object::ObjectType as _,prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_,pin::Pin};

glib::wrapper! {
    #[doc(alias = "LightDMGreeter")]
    pub struct Greeter(Object<ffi::LightDMGreeter, ffi::LightDMGreeterClass>);

    match fn {
        type_ => || ffi::lightdm_greeter_get_type(),
    }
}

impl Greeter {
        pub const NONE: Option<&'static Greeter> = None;
    

    #[doc(alias = "lightdm_greeter_new")]
    pub fn new() -> Greeter {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::lightdm_greeter_new())
        }
    }
}

impl Default for Greeter {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

pub trait GreeterExt: IsA<Greeter> + 'static {
    #[doc(alias = "lightdm_greeter_authenticate")]
    fn authenticate(&self, username: Option<&str>) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_authenticate(self.as_ref().to_glib_none().0, username.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_authenticate_as_guest")]
    fn authenticate_as_guest(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_authenticate_as_guest(self.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_authenticate_autologin")]
    fn authenticate_autologin(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_authenticate_autologin(self.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_authenticate_remote")]
    fn authenticate_remote(&self, session: &str, username: Option<&str>) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_authenticate_remote(self.as_ref().to_glib_none().0, session.to_glib_none().0, username.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_cancel_authentication")]
    fn cancel_authentication(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_cancel_authentication(self.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_cancel_autologin")]
    fn cancel_autologin(&self) {
        unsafe {
            ffi::lightdm_greeter_cancel_autologin(self.as_ref().to_glib_none().0);
        }
    }

    #[cfg_attr(feature = "v1_11_1", deprecated = "Since 1.11.1")]
    #[allow(deprecated)]
    #[doc(alias = "lightdm_greeter_connect_sync")]
    fn connect_sync(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_connect_sync(self.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_connect_to_daemon")]
    fn connect_to_daemon<P: FnOnce(Result<(), glib::Error>) + 'static>(&self, cancellable: Option<&impl IsA<gio::Cancellable>>, callback: P) {
        
                let main_context = glib::MainContext::ref_thread_default();
                let is_main_context_owner = main_context.is_owner();
                let has_acquired_main_context = (!is_main_context_owner)
                    .then(|| main_context.acquire().ok())
                    .flatten();
                assert!(
                    is_main_context_owner || has_acquired_main_context.is_some(),
                    "Async operations only allowed if the thread is owning the MainContext"
                );
        
        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn connect_to_daemon_trampoline<P: FnOnce(Result<(), glib::Error>) + 'static>(_source_object: *mut glib::gobject_ffi::GObject, res: *mut gio::ffi::GAsyncResult, user_data: glib::ffi::gpointer) { unsafe {
            let mut error = std::ptr::null_mut();
            ffi::lightdm_greeter_connect_to_daemon_finish(_source_object as *mut _, res, &mut error);
            let result = if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) };
            let callback: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::from_raw(user_data as *mut _);
            let callback: P = callback.into_inner();
            callback(result);
        }}
        let callback = connect_to_daemon_trampoline::<P>;
        unsafe {
            ffi::lightdm_greeter_connect_to_daemon(self.as_ref().to_glib_none().0, cancellable.map(|p| p.as_ref()).to_glib_none().0, Some(callback), Box_::into_raw(user_data) as *mut _);
        }
    }

    
    fn connect_to_daemon_future(&self) -> Pin<Box_<dyn std::future::Future<Output = Result<(), glib::Error>> + 'static>> {

        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.connect_to_daemon(
                Some(cancellable),
                move |res| {
                    send.resolve(res);
                },
            );
        }))
    }

    #[doc(alias = "lightdm_greeter_connect_to_daemon_sync")]
    fn connect_to_daemon_sync(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_connect_to_daemon_sync(self.as_ref().to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_ensure_shared_data_dir")]
    fn ensure_shared_data_dir<P: FnOnce(Result<glib::GString, glib::Error>) + 'static>(&self, username: &str, cancellable: Option<&impl IsA<gio::Cancellable>>, callback: P) {
        
                let main_context = glib::MainContext::ref_thread_default();
                let is_main_context_owner = main_context.is_owner();
                let has_acquired_main_context = (!is_main_context_owner)
                    .then(|| main_context.acquire().ok())
                    .flatten();
                assert!(
                    is_main_context_owner || has_acquired_main_context.is_some(),
                    "Async operations only allowed if the thread is owning the MainContext"
                );
        
        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn ensure_shared_data_dir_trampoline<P: FnOnce(Result<glib::GString, glib::Error>) + 'static>(_source_object: *mut glib::gobject_ffi::GObject, res: *mut gio::ffi::GAsyncResult, user_data: glib::ffi::gpointer) { unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::lightdm_greeter_ensure_shared_data_dir_finish(_source_object as *mut _, res, &mut error);
            let result = if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) };
            let callback: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::from_raw(user_data as *mut _);
            let callback: P = callback.into_inner();
            callback(result);
        }}
        let callback = ensure_shared_data_dir_trampoline::<P>;
        unsafe {
            ffi::lightdm_greeter_ensure_shared_data_dir(self.as_ref().to_glib_none().0, username.to_glib_none().0, cancellable.map(|p| p.as_ref()).to_glib_none().0, Some(callback), Box_::into_raw(user_data) as *mut _);
        }
    }

    
    fn ensure_shared_data_dir_future(&self, username: &str) -> Pin<Box_<dyn std::future::Future<Output = Result<glib::GString, glib::Error>> + 'static>> {

        let username = String::from(username);
        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.ensure_shared_data_dir(
                &username,
                Some(cancellable),
                move |res| {
                    send.resolve(res);
                },
            );
        }))
    }

    #[doc(alias = "lightdm_greeter_ensure_shared_data_dir_sync")]
    fn ensure_shared_data_dir_sync(&self, username: &str) -> Result<glib::GString, glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let ret = ffi::lightdm_greeter_ensure_shared_data_dir_sync(self.as_ref().to_glib_none().0, username.to_glib_none().0, &mut error);
            if error.is_null() { Ok(from_glib_full(ret)) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_get_authentication_user")]
    #[doc(alias = "get_authentication_user")]
    #[doc(alias = "authentication-user")]
    fn authentication_user(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_authentication_user(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_autologin_guest_hint")]
    #[doc(alias = "get_autologin_guest_hint")]
    #[doc(alias = "autologin-guest-hint")]
    fn is_autologin_guest_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_autologin_guest_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_autologin_session_hint")]
    #[doc(alias = "get_autologin_session_hint")]
    #[doc(alias = "autologin-session-hint")]
    fn autologin_session_hint(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_autologin_session_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_autologin_timeout_hint")]
    #[doc(alias = "get_autologin_timeout_hint")]
    #[doc(alias = "autologin-timeout-hint")]
    fn autologin_timeout_hint(&self) -> i32 {
        unsafe {
            ffi::lightdm_greeter_get_autologin_timeout_hint(self.as_ref().to_glib_none().0)
        }
    }

    #[doc(alias = "lightdm_greeter_get_autologin_user_hint")]
    #[doc(alias = "get_autologin_user_hint")]
    #[doc(alias = "autologin-user-hint")]
    fn autologin_user_hint(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_autologin_user_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_default_session_hint")]
    #[doc(alias = "get_default_session_hint")]
    #[doc(alias = "default-session-hint")]
    fn default_session_hint(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_default_session_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_has_guest_account_hint")]
    #[doc(alias = "get_has_guest_account_hint")]
    #[doc(alias = "has-guest-account-hint")]
    fn has_guest_account_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_has_guest_account_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_hide_users_hint")]
    #[doc(alias = "get_hide_users_hint")]
    #[doc(alias = "hide-users-hint")]
    fn hides_users_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_hide_users_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_hint")]
    #[doc(alias = "get_hint")]
    fn hint(&self, name: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_hint(self.as_ref().to_glib_none().0, name.to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_in_authentication")]
    #[doc(alias = "get_in_authentication")]
    #[doc(alias = "in-authentication")]
    fn is_in_authentication(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_in_authentication(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_is_authenticated")]
    #[doc(alias = "get_is_authenticated")]
    #[doc(alias = "is-authenticated")]
    fn is_authenticated(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_is_authenticated(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_lock_hint")]
    #[doc(alias = "get_lock_hint")]
    #[doc(alias = "lock-hint")]
    fn is_lock_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_lock_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_select_guest_hint")]
    #[doc(alias = "get_select_guest_hint")]
    #[doc(alias = "select-guest-hint")]
    fn selects_guest_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_select_guest_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_select_user_hint")]
    #[doc(alias = "get_select_user_hint")]
    #[doc(alias = "select-user-hint")]
    fn select_user_hint(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_greeter_get_select_user_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_show_manual_login_hint")]
    #[doc(alias = "get_show_manual_login_hint")]
    #[doc(alias = "show-manual-login-hint")]
    fn shows_manual_login_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_show_manual_login_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_get_show_remote_login_hint")]
    #[doc(alias = "get_show_remote_login_hint")]
    #[doc(alias = "show-remote-login-hint")]
    fn shows_remote_login_hint(&self) -> bool {
        unsafe {
            from_glib(ffi::lightdm_greeter_get_show_remote_login_hint(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_greeter_respond")]
    fn respond(&self, response: &str) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_respond(self.as_ref().to_glib_none().0, response.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_set_language")]
    fn set_language(&self, language: &str) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_set_language(self.as_ref().to_glib_none().0, language.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "lightdm_greeter_set_resettable")]
    fn set_resettable(&self, resettable: bool) {
        unsafe {
            ffi::lightdm_greeter_set_resettable(self.as_ref().to_glib_none().0, resettable.into_glib());
        }
    }

    #[doc(alias = "lightdm_greeter_start_session")]
    fn start_session<P: FnOnce(Result<(), glib::Error>) + 'static>(&self, session: Option<&str>, cancellable: Option<&impl IsA<gio::Cancellable>>, callback: P) {
        
                let main_context = glib::MainContext::ref_thread_default();
                let is_main_context_owner = main_context.is_owner();
                let has_acquired_main_context = (!is_main_context_owner)
                    .then(|| main_context.acquire().ok())
                    .flatten();
                assert!(
                    is_main_context_owner || has_acquired_main_context.is_some(),
                    "Async operations only allowed if the thread is owning the MainContext"
                );
        
        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn start_session_trampoline<P: FnOnce(Result<(), glib::Error>) + 'static>(_source_object: *mut glib::gobject_ffi::GObject, res: *mut gio::ffi::GAsyncResult, user_data: glib::ffi::gpointer) { unsafe {
            let mut error = std::ptr::null_mut();
            ffi::lightdm_greeter_start_session_finish(_source_object as *mut _, res, &mut error);
            let result = if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) };
            let callback: Box_<glib::thread_guard::ThreadGuard<P>> = Box_::from_raw(user_data as *mut _);
            let callback: P = callback.into_inner();
            callback(result);
        }}
        let callback = start_session_trampoline::<P>;
        unsafe {
            ffi::lightdm_greeter_start_session(self.as_ref().to_glib_none().0, session.to_glib_none().0, cancellable.map(|p| p.as_ref()).to_glib_none().0, Some(callback), Box_::into_raw(user_data) as *mut _);
        }
    }

    
    fn start_session_future(&self, session: Option<&str>) -> Pin<Box_<dyn std::future::Future<Output = Result<(), glib::Error>> + 'static>> {

        let session = session.map(ToOwned::to_owned);
        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.start_session(
                session.as_ref().map(::std::borrow::Borrow::borrow),
                Some(cancellable),
                move |res| {
                    send.resolve(res);
                },
            );
        }))
    }

    #[doc(alias = "lightdm_greeter_start_session_sync")]
    fn start_session_sync(&self, session: Option<&str>) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lightdm_greeter_start_session_sync(self.as_ref().to_glib_none().0, session.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }

    #[doc(alias = "authentication-complete")]
    fn connect_authentication_complete<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn authentication_complete_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"authentication-complete".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(authentication_complete_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "autologin-timer-expired")]
    fn connect_autologin_timer_expired<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn autologin_timer_expired_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"autologin-timer-expired".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(autologin_timer_expired_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "idle")]
    fn connect_idle<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn idle_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"idle".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(idle_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "reset")]
    fn connect_reset<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn reset_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"reset".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(reset_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "show-message")]
    fn connect_show_message<F: Fn(&Self, &str, MessageType) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_message_trampoline<P: IsA<Greeter>, F: Fn(&P, &str, MessageType) + 'static>(this: *mut ffi::LightDMGreeter, text: *mut std::ffi::c_char, type_: ffi::LightDMMessageType, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref(), &glib::GString::from_glib_borrow(text), from_glib(type_))
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"show-message".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(show_message_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "show-prompt")]
    fn connect_show_prompt<F: Fn(&Self, &str, PromptType) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn show_prompt_trampoline<P: IsA<Greeter>, F: Fn(&P, &str, PromptType) + 'static>(this: *mut ffi::LightDMGreeter, text: *mut std::ffi::c_char, type_: ffi::LightDMPromptType, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref(), &glib::GString::from_glib_borrow(text), from_glib(type_))
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"show-prompt".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(show_prompt_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "authentication-user")]
    fn connect_authentication_user_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_authentication_user_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::authentication-user".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_authentication_user_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "autologin-guest-hint")]
    fn connect_autologin_guest_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_autologin_guest_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::autologin-guest-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_autologin_guest_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "autologin-session-hint")]
    fn connect_autologin_session_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_autologin_session_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::autologin-session-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_autologin_session_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "autologin-timeout-hint")]
    fn connect_autologin_timeout_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_autologin_timeout_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::autologin-timeout-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_autologin_timeout_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "autologin-user-hint")]
    fn connect_autologin_user_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_autologin_user_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::autologin-user-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_autologin_user_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "default-session-hint")]
    fn connect_default_session_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_default_session_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::default-session-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_default_session_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "has-guest-account-hint")]
    fn connect_has_guest_account_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_has_guest_account_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::has-guest-account-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_has_guest_account_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "hide-users-hint")]
    fn connect_hide_users_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_hide_users_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::hide-users-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_hide_users_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "in-authentication")]
    fn connect_in_authentication_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_in_authentication_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::in-authentication".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_in_authentication_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "is-authenticated")]
    fn connect_is_authenticated_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_is_authenticated_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::is-authenticated".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_is_authenticated_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "lock-hint")]
    fn connect_lock_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_lock_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::lock-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_lock_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "select-guest-hint")]
    fn connect_select_guest_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_select_guest_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::select-guest-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_select_guest_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "select-user-hint")]
    fn connect_select_user_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_select_user_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::select-user-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_select_user_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "show-manual-login-hint")]
    fn connect_show_manual_login_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_show_manual_login_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::show-manual-login-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_show_manual_login_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "show-remote-login-hint")]
    fn connect_show_remote_login_hint_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_show_remote_login_hint_trampoline<P: IsA<Greeter>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMGreeter, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Greeter::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::show-remote-login-hint".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_show_remote_login_hint_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<Greeter>> GreeterExt for O {}
