// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "LightDMLanguage")]
    pub struct Language(Object<ffi::LightDMLanguage, ffi::LightDMLanguageClass>);

    match fn {
        type_ => || ffi::lightdm_language_get_type(),
    }
}

impl Language {
        pub const NONE: Option<&'static Language> = None;
    
}

pub trait LanguageExt: IsA<Language> + 'static {
    #[doc(alias = "lightdm_language_get_code")]
    #[doc(alias = "get_code")]
    fn code(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_code(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_language_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_name(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_language_get_territory")]
    #[doc(alias = "get_territory")]
    fn territory(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_language_get_territory(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_language_matches")]
    fn matches(&self, code: &str) -> bool {
        unsafe {
            from_glib(ffi::lightdm_language_matches(self.as_ref().to_glib_none().0, code.to_glib_none().0))
        }
    }

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMLanguage, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::name".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_name_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "territory")]
    fn connect_territory_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_territory_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(this: *mut ffi::LightDMLanguage, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) { unsafe {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }}
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, c"notify::territory".as_ptr(),
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_territory_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<Language>> LanguageExt for O {}
