// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "LightDMLayout")]
    pub struct Layout(Object<ffi::LightDMLayout, ffi::LightDMLayoutClass>);

    match fn {
        type_ => || ffi::lightdm_layout_get_type(),
    }
}

impl Layout {
        pub const NONE: Option<&'static Layout> = None;
    
}

pub trait LayoutExt: IsA<Layout> + 'static {
    #[doc(alias = "lightdm_layout_get_description")]
    #[doc(alias = "get_description")]
    fn description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_layout_get_description(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_layout_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_layout_get_name(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "lightdm_layout_get_short_description")]
    #[doc(alias = "get_short_description")]
    #[doc(alias = "short-description")]
    fn short_description(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::lightdm_layout_get_short_description(self.as_ref().to_glib_none().0))
        }
    }
}

impl<O: IsA<Layout>> LayoutExt for O {}
